### ISSUE TITLE
IP Adresse & Windows Title werden nicht gespeichert

### ISSUE THREAD

**Issue by Dtrieb** [MinersWin/Scrcpy-Desktop#4]
Jedes mal muss ich IP Adresse & Windows Title eingeben, da sie nicht gespeichert werden.
Das wäre schön wenn sie gespeichert werden.

**Comment by MinersWin** [comment]
Koennte man sich mal fuer ein Zukuenftiges Update ueberlegen. 
Hat in unseren Augen allerdings keine hohe Prioritaet. 
Wir versuchen erstmal die Virenproblematik in den Griff zu kriegen. ;)
