### ISSUE TITLE
Gets identified as Virus

### ISSUE THREAD

**Issue by hofq** [MinersWin/Scrcpy-Desktop#5]
Windows Indentify the Installer as Virus. 

Is that an known bug?

**Comment by hofq** [comment]
![image](https://user-images.githubusercontent.com/54744977/113487770-35a89280-94ba-11eb-8d82-af5e62be00b7.png)
Fehlermeldung in Defender
  
  
![image](https://user-images.githubusercontent.com/54744977/113487805-625caa00-94ba-11eb-842e-b4a1b85cdf89.png)
Fehler in Edge

**Comment by MinersWin** [comment]
Tiefgreifende Systemänderungen werden häufig von Viren gemacht und sind ohne teure Zertifikate und Audits deswegen von Virenscannern als Bedrohung eingestuft. Zum Beispiel ändern wir etwas an der Hosts Datei um zum Beispiel die Microsoft Telemetrie Server zu blockieren. Dies wird allerdings auch häufig von Viren gemacht um z.B. einfachere Man in the Middle Attacken oder ähnliches auszuführen.
Von daher das Tool ist Clean, allerdings nicht in den Augen der AV Hersteller. Ich bin nicht bereit oder überhaupt in der Lage mir teure Zertifikate in hohen dreistelligen Beträgen zu kaufen und die AV Hersteller um Audits anzufragen, welche nach jeden Update sowieso wieder erneuert werden müssen. Hierfür fehlen mir Leider einfach die Zeit und Mittel.
Am besten den Virenschutz vor dem Ausführen deaktivieren dann sollte dies kein Problem sein.

Bugreports und Featurewünsche können gerne auf GitHub gepostet werden, bitte dabei folgendes Beachten: https://bugreport.scrcpy.miners.win/
GitHub Releases: https://github.com/MinersWin/Scrcpy-Desktop/releases/
Alternativer Downloadlink: http://cdn.thegeekfreaks.de/Download/Releases/Scrcpy-Desktop/v_2_0/scrcpy.exe
